# Generated by Django 4.1.7 on 2023-03-12 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_slug_alter_category_slug_alter_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="tags",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag_blogs",
                to="blog.tag",
            ),
        ),
    ]
